### ISSUE TITLE
Tried simple example, got "RuntimeError: Tried to run fill-in instruction for opcode 72"

### ISSUE THREAD

**Issue by dylanmc** [kc0bfv/pcode-emulator#1]
I created a simple fibonacci program and loaded it up in Ghidra 9.2.2, selected the function, and ran the "pcode_interpreter.py" script from Script Manager. It seems to have completed the interpretation, but crashed at the `return` line of the function.

Here's the stack trace:
```
Current location: main+0x0(0x100003fa0)
Traceback (most recent call last):
  File "/Users/.../ghidra_scripts/pcode_interpreter.py", line 135, in <module>   
    main()                    
  File "/Users/.../ghidra_scripts/pcode_interpreter.py", line 132, in main                 
    analyze_func_at(curr_addr)                                        
  File "/Users/.../ghidra_scripts/pcode_interpreter.py", line 94, in analyze_func_at 
    run_pcode(containing_func, state, state.arch.sentinel_return_addr)
  File "/Users/.../ghidra_scripts/pcode_interpreter.py", line 53, in run_pcode                            cur_loc = state.execute_cur_location()
  File "/Users/.../ghidra_scripts/ghidra_pcode_interpreter/state.py", line 20, in execute_cur_location
    return self._step_cur_loc(True)
  File "/Users/.../ghidra_scripts/ghidra_pcode_interpreter/state.py", line 40, in _step_cur_loc
    instr.execute(self)                                                                         
  File "/Users/.../ghidra_scripts/ghidra_pcode_interpreter/instr.py", line 41, in execute
    ret = self._simple_exec_handler(state, inputs)                                                      File "/Users/.../ghidra_scripts/ghidra_pcode_interpreter/instr.py", line 97, in _simple_exec_handler
    raise RuntimeError("Tried to run fill-in instruction for opcode {}"
RuntimeError: Tried to run fill-in instruction for opcode 72
```

PCode opcode 72 is indeed the placeholder for out-of-bounds. Maybe an issue with the Ghidra version?

**Comment by dylanmc** [comment]
Figured it out - there's a new PCode opcode - I've implemented it. Pull request incoming.

**Comment by kc0bfv** [comment]
Thanks dylan - should be gtg now.  I'm sorry I haven't added some of the other significant advancements I had hoped for with this project.  Work is taking up too much time.
